name: basic
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  hive: ^2.2.3
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.3
  hive_flutter: ^1.1.0
  firebase_core: ^2.31.1
  firebase_auth: ^4.4.1
  cloud_firestore: ^4.17.4
  flutter_secure_storage: ^9.2.2
  google_sign_in: ^5.4.3
  bot_toast: ^4.1.3
  flutter_svg_provider: ^1.0.7
  photo_manager: ^3.2.3
  wechat_assets_picker: ^8.6.2
  board_datetime_picker: ^2.1.1
  flutter_localization: ^0.2.1
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/bottom_nav/